name: Publish and Release WoW Sims App

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0

jobs:
  build:
    name: Build Application
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # Targeting .NET 9

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release -p:Version=${{ github.ref_name }}

      - name: Publish Application
        run: dotnet publish -c Release -o ./publish --self-contained -p:PublishSingleFile=true -p:Version=${{ github.ref_name }}

      - name: Archive Build Artifacts
        run: |
          mkdir -p artifacts
          powershell Compress-Archive -Path ./publish/* -DestinationPath artifacts/WoWSimsApp.zip

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WoWSimsApp
          path: artifacts/WoWSimsApp.zip

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: WoWSimsApp

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automated release for WoW Sims Launcher.
            - Version: ${{ github.ref_name }}
          artifacts: WoWSimsApp.zip
